apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: kubehome
      protocol: layer2
      addresses:
      - 192.168.110.10-192.168.110.199
      avoid-buggy-ips: true
      auto-assign: true
