apiVersion: v1
kind: Namespace
metadata:
  name: kube-verify
  labels:
    app: kube-verify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: kube-verify
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
