apiVersion: v1
kind: Service
metadata:
  name: kube-verify
  namespace: kube-verify
spec:
  selector:
    run: load-balancer-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
